-- AlterTable
ALTER TABLE "net_worth_snapshots" ADD COLUMN     "cashValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "investmentValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "otherAssetsValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
