import {
  GoogleGenerativeAI,
  type GenerationConfig,
} from "@google/generative-ai";
import type {
  AiCompletionOptions,
  AiCompletionResult,
  AiMessage,
  AiProviderClient,
} from "./types";

export class GeminiProvider implements AiProviderClient {
  private genAI: GoogleGenerativeAI;
  private model: string;

  constructor(apiKey: string, model: string) {
    this.genAI = new GoogleGenerativeAI(apiKey);
    // Ensure we default to the high-performance MoE model
    this.model = model || "gemma-4-26b-a4b-it";
  }

  /**
   * Optimizes history by removing previous "thinking" blocks.
   * Gemma-4 performs significantly faster when history is clean of reasoning tags.
   */
  private toGeminiHistory(messages: AiMessage[]) {
    return messages
      .filter((m) => m.role !== "system")
      .map((m) => {
        // Strip out any <|channel>thought ... <channel|> blocks from previous turns
        const cleanContent = m.content
          .replace(/<\|channel>thought[\s\S]*?<channel\|>/g, "")
          .trim();
        return {
          role: m.role === "assistant" ? "model" : "user",
          parts: [{ text: cleanContent }],
        };
      });
  }

  /**
   * Fast configuration for Gemma-4 MoE architecture.
   */
  private getFastGenerationConfig(): GenerationConfig {
    return {
      temperature: 1.0,
      topP: 0.95,
      topK: 1, // Greedy search: fastest inference path
      maxOutputTokens: 1024,
    };
  }

  /**
   * Injects the "No-Thinking" instruction to bypass reasoning latency.
   */
  private getSystemInstruction(userPrompt?: string): string {
    const base = userPrompt || "You are a helpful assistant.";
    // Gemma-4: Removing <|think|> from system prompt is the primary way to disable reasoning mode.
    return `${base}\nRespond directly and concisely. Do not use internal reasoning or thinking tags.`;
  }

  async complete(opts: AiCompletionOptions): Promise<AiCompletionResult> {
    const genModel = this.genAI.getGenerativeModel({
      model: this.model,
      systemInstruction: this.getSystemInstruction(opts.systemPrompt),
      generationConfig: this.getFastGenerationConfig(),
    });

    const history = this.toGeminiHistory(opts.messages.slice(0, -1));
    const lastMsg = opts.messages[opts.messages.length - 1];
    const chat = genModel.startChat({ history });

    const result = await chat.sendMessage(lastMsg?.content ?? "");
    const text = result.response.text();

    return { content: text };
  }

  async completeStream(
    opts: AiCompletionOptions,
    onToken: (token: string) => void,
  ): Promise<AiCompletionResult> {
    const genModel = this.genAI.getGenerativeModel({
      model: this.model,
      systemInstruction: this.getSystemInstruction(opts.systemPrompt),
      generationConfig: this.getFastGenerationConfig(),
    });

    const history = this.toGeminiHistory(opts.messages.slice(0, -1));
    const lastMsg = opts.messages[opts.messages.length - 1];
    const chat = genModel.startChat({ history });

    const result = await chat.sendMessageStream(lastMsg?.content ?? "");

    let fullContent = "";
    for await (const chunk of result.stream) {
      if (opts.signal?.aborted) break;
      const token = chunk.text();

      // Filter out accidental empty thought blocks generated by the model
      if (token && !token.includes("<|channel>thought")) {
        onToken(token);
        fullContent += token;
      }
    }

    return { content: fullContent };
  }

  async validateApiKey(): Promise<boolean> {
    try {
      // Use a minimal model for validation to save costs/time
      const genModel = this.genAI.getGenerativeModel({
        model: this.model,
      });
      await genModel.generateContent({
        contents: [{ role: "user", parts: [{ text: "hi" }] }],
        generationConfig: { maxOutputTokens: 1 },
      });
      return true;
    } catch {
      return false;
    }
  }
}
